name: 'Prepare common repo'
description: 'Action to checkout common repo'

runs:
  using: "composite"
  steps:
    - name: Check branch name
      shell: bash
      run: cd common && pwd && ls -la && npm install && rm -rf ./.git && node --loader ts-node/esm ./checkBranchName.ts