name: Workflow A
on:
  pull_request:
    branches:
      - develop
      - master
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:

jobs:
  Jobs-B:
    name: Job B
    runs-on: ubuntu-latest
    steps:
      - name: Hello World B from TestRepo2
        run: echo "Hello World B"

  integration_tests-tcc:
    needs: Jobs-B
    uses: gladykov/TestRepo2/.github/workflows/workflow_b.yml@main
    secrets: inherit
