name: Workflow A
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:
#  schedule:
#    - cron: '*/10 * * * *'

jobs:
  integration-tests:
    name: Integration tests
    runs-on:
      labels: ${{ inputs.testRunner }}
    steps:
      - name: Push results to Test Results Analyzer
        # Collect only results from nightly runs
        env:
          CATEGORY: ${{ github.event_name }} - ${{ github.workspace }}
        # We don't want to block pipelines during development phase, so always return 0
        run: echo $category
