name: Integration tests MMC

on:
  schedule:
    # Run the tests at 12:23 AM everyday
    - cron: '23 0 * * *'
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - production

permissions:
  contents: read
  checks: write

jobs:
  wait_for_staging_deployment:
    name: Wait for staging deployment
    if: ${{github.event_name == 'pull_request' && github.base_ref == 'production'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Wait on workflow
        env:
          WORKFLOW: 'deploy.yml'
          REPOSITORY: ${{ github.repository }}
          INTERVAL: 30
          TIMEOUT: 30
          SHA: ${{ github.event.pull_request.head.sha }}
          GH_TOKEN: ${{ github.token }}
        run: .github/wait-for-deployment.sh
  
  
  integration_tests-mmc:
    if: ${{ always() && (needs.wait_for_staging_deployment.result == 'success' || needs.wait_for_staging_deployment.result == 'skipped') }}
    needs: wait_for_staging_deployment
    runs-on: ubuntu-latest
    steps:
      - name: Finished wait
        run: echo 'i finished waiting here'
