name: Workflow A
on:
  pull_request:
    branches:
      - develop
      - master
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:
  workflow_call:

jobs:
  Jobs-B:
    name: Job B
    runs-on: ubuntu-latest
    steps:
      - name: Hello World B from TestRepo2
        run: echo "Hello World B"
      - name: Dump GitHub context A
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  integration_tests-tcc:
    needs: Jobs-B
    uses: gladykov/TestRepo2/.github/workflows/workflow_b.yml@main
    secrets: inherit
