name: Workflow A
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  Jobs-B:
    name: Job B
    uses: gladykov/TestRepo2/.github/workflows/workflow_b.yml@main
    secrets: inherit
