name: Workflow A
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Jobs-B:
    name: Job B
    runs-on: ubuntu-latest
    steps:
      - name: Publish M unit test report
        uses: dorny/test-reporter@d61b558e8df85cb60d09ca3e5b09653b4477cea7 # pin@v1
        if: success() || failure()
        with:
          name: M unit tests report
          path: mmc/junit.xml
          reporter: jest-junit
          #           max-annotations: '0'  # https://github.com/dorny/test-reporter/issues/131
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@0303d6b62e310685c0e34d0b9cde218036885c4d # pin@v3
        if: ${{(github.event_name == 'pull_request' && github.base_ref == 'main' && always()) || (github.event_name == 'push' && always()) || (github.event_name == 'workflow_dispatch' && always())}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # pin@v4
        if: ${{(github.event_name == 'pull_request' && github.base_ref == 'main' && always()) || (github.event_name == 'push' && always()) || (github.event_name == 'workflow_dispatch' && always())}}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Check if there are changes to files
        uses: tj-actions/verify-changed-files@eb6d385c0e52fb28e2f6b70e15c835cb3cbfff17 # pin@v18
        id: verify-changed-files
        with:
          read-gitignore: true
      - name: Create PR
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: devops-infra/action-pull-request@e66e2ba93519dc63b9884a26e620e2fd0cffab2c # pin@v0.5.5
        with:
          github_token: ${{ secrets.PAT }}
          source_branch: ${{ env.BRANCH_NAME }}
          target_branch: main
          title: ${{ env.PR_TITLE }}
