name: 'Prepare common repo'
description: 'Action to checkout common repo'

runs:
  using: "composite"
  steps:
    - name: Check branch name
      run: |
        rm -rf ./.git
        npm ci
        node --loader ts-node/esm ./checkBranchName.ts
      workdir: common