name: Workflow A
on:
  pull_request:
    branches:
      - develop
      - master
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:

jobs:
  integration_tests-tcc:
    name: Name for workflow A
    uses: ./.github/workflows/workflow_b.yml
    secrets: inherit
